
services:
  blog:
    container_name: blog
    build: ./blog
    command: bash -c "python ./manage.py makemigrations --noinput && python ./manage.py migrate --noinput && python ./manage.py collectstatic --noinput && python ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - storage_volume:/app/storage
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - storage_volume:/app/storage
      - static_volume:/app/staticfiles
    ports:
      # - 80:80 # Nginx 外部端口80（http默认端口），内部端口80
      - 443:443 # Nginx 外部端口443（https默认端口），内部端口443
    depends_on:
      - blog # depends_on 告诉up的时候应该先运行

volumes:
  storage_volume:
  static_volume:
